---
title: "Reading Data"
author: "Jeff Goldsmith"
date: "10/23/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(httr)
```

## Scraping

### NSDUH Table

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```

That's step one!

```{r}
drug_use_xml %>%
  html_nodes(css = "table")
```

Got the table(s) ...

```{r}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table() %>%
  .[-1,] %>% 
  as_tibble()
```

Now I have exactly the table I want!!

### NYC Cost of living table

I'd like to understand the impact of my life choices by looking at cost of living in NYC compared to the rest of the US. The table below should help!

```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

nyc_cost_xml = read_html(url)

nyc_cost_table = (nyc_cost_xml %>% html_nodes(css = "table"))[[2]] %>% 
  html_table(header = TRUE)
```




## APIs


